#!/bin/bash

# Converts scrapped epicurious data to vector format.

# Exit script on first failure
set -e

# Echo commands to stdout.
set -x

src/data/clean_data.py --epi -v
src/features/create_features.py --epi -v
src/data/recipe2vec.py --epi -v