#!/bin/bash

# Trains a new CRF model given a set of labelled data.

# Exit script on first failure
set -e

# Echo commands to stdout.
set -x

#src/data/clean_data.py --crf -v
src/features/create_features.py --crf -v
src/features/create_training_labels.py
src/models/train_crf_model.py